### PR TITLE
New function: TikZ preview

### PR DESCRIPTION
**Pull request by PhilippImhof**
Added new function to preview TikZ drawings.

This leads to a new dependency: `@atom/temp` is needed to create temporary folder.

Also, user must have ImageMagick installed, because the implementation uses `convert` to convert PDF to PNG.  As an alternative, we could use Ghostscript and convert PS to PNG. But as PS does not fully support transparency, this means the quality is worse.

### CODE REVIEW

**Comment by PhilippImhof** [comment]
I also increased the version number, did not know whether that was necessary in order for Atom to use my local version instead of the one fetched from the library. It actually wasn't, as I understand.

**Comment by mangecoeur** [comment]
bit confused, you closed this PR?

**Comment by PhilippImhof** [comment]
Yes, I'm sorry. I should not have sent it. I am currently working on a better method. I realized that what I prepared was more some sort of a quick and dirty hack than a clean solution. I will create another PR in some time.

**Comment by mangecoeur** [comment]
ok thanks.

**Pull request closed without merging**
